import sys
path = r'lib/macos-data.ts'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

old_start = content.find('export const finderProjects')
old_end = content.find('\nexport const socialLinks', old_start)
print(f'start={old_start} end={old_end}', file=sys.stderr)
if old_start == -1 or old_end == -1:
    print('not found', file=sys.stderr)
    sys.exit(1)

new_block = (
    'export const finderProjects: Record<\n'
    '  FinderCategoryId,\n'
    '  Array<{\n'
    '    name: string;\n'
    '    year: string;\n'
    '    summary: string;\n'
    '    href: string;\n'
    '    accentFrom: string;\n'
    '    accentTo: string;\n'
    '  }>\n'
    '> = {\n'
    '  web: [\n'
    '    {\n'
    '      name: "FC Fulbert",\n'
    '      year: "2025",\n'
    '      summary: "Refonte SEO et hi\u00e9rarchie de contenu pour un site plus lisible.",\n'
    '      href: "/pages/projects/fc-fulbert.html",\n'
    '      accentFrom: "#8EDFFF",\n'
    '      accentTo: "#2A73FF"\n'
    '    },\n'
    '    {\n'
    '      name: "Zoo Fulbert",\n'
    '      year: "2025",\n'
    '      summary: "Site vitrine fictif illustrant la taxonomy et l\'architecture CMS.",\n'
    '      href: "#",\n'
    '      accentFrom: "#A8F5D0",\n'
    '      accentTo: "#0D9355"\n'
    '    },\n'
    '    {\n'
    '      name: "Portfolio macOS",\n'
    '      year: "2025",\n'
    '      summary: "Simulation bureau Apple : fen\u00eatres drag, traffic lights et GSAP.",\n'
    '      href: "#",\n'
    '      accentFrom: "#F5B7FF",\n'
    '      accentTo: "#FF6464"\n'
    '    }\n'
    '  ],\n'
    '  apps: [\n'
    '    {\n'
    '      name: "IronPulse",\n'
    '      year: "2025",\n'
    '      summary: "Dashboard sport et nutrition pens\u00e9 comme une app produit.",\n'
    '      href: "/pages/projects/ironpulse.html",\n'
    '      accentFrom: "#9EF0C5",\n'
    '      accentTo: "#31B66F"\n'
    '    },\n'
    '    {\n'
    '      name: "App Action",\n'
    '      year: "2025",\n'
    '      summary: "D\u00e9mo produit avec dashboards et parcours d\'administration.",\n'
    '      href: "/pages/projects/app-action.html",\n'
    '      accentFrom: "#A3D7FF",\n'
    '      accentTo: "#566BFF"\n'
    '    },\n'
    '    {\n'
    '      name: "Resolution Mate",\n'
    '      year: "2025",\n'
    '      summary: "Suivi d\'objectifs avec filtres, progression et pilotage personnel.",\n'
    '      href: "/pages/projects/resolution-mate.html",\n'
    '      accentFrom: "#C7D2FF",\n'
    '      accentTo: "#6981FF"\n'
    '    },\n'
    '    {\n'
    '      name: "Mini Wiki PHP",\n'
    '      year: "2024",\n'
    '      summary: "Wiki minimaliste en PHP avec CRUD et rendu c\u00f4t\u00e9 serveur.",\n'
    '      href: "#",\n'
    '      accentFrom: "#FFD0A0",\n'
    '      accentTo: "#C05500"\n'
    '    }\n'
    '  ],\n'
    '  future: [\n'
    '    {\n'
    '      name: "Projet Rust",\n'
    '      year: "Soon",\n'
    '      summary: "Exploration Rust et WebAssembly pour des rendus interactifs hautes performances.",\n'
    '      href: "#",\n'
    '      accentFrom: "#FFAB70",\n'
    '      accentTo: "#D64D00"\n'
    '    }\n'
    '  ]\n'
    '};'
)

new_content = content[:old_start] + new_block + content[old_end:]
with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)
print('done', file=sys.stderr)
