NEW_DATA = (
"const finderCategoryLabels = {\n"
"    web:    'Sites web',\n"
"    apps:   'Applications',\n"
"    future: '\u00c0 venir'\n"
"};\n"
"\n"
"const finderProjects = {\n"
"    web: [\n"
"        {\n"
"            title: 'FC Fulbert',\n"
"            status: 'live',\n"
"            statusLabel: 'En ligne',\n"
"            year: '2025',\n"
"            stack: ['HTML', 'CSS', 'SEO'],\n"
"            summary: 'Refonte compl\u00e8te du site officiel d\u2019un club de football. Hi\u00e9rarchie \u00e9ditoriale, performances SEO et navigation mobile-first.',\n"
"            href: 'projets/fc-fulbert.html',\n"
"            accent: ['#1D4ED8', '#1e3a8a'],\n"
"            symbol: '\u26bd'\n"
"        },\n"
"        {\n"
"            title: 'Zoo Fulbert',\n"
"            status: 'live',\n"
"            statusLabel: 'En ligne',\n"
"            year: '2025',\n"
"            stack: ['HTML', 'CSS', 'JavaScript'],\n"
"            summary: 'Site vitrine pour un parc zoologique cugex. Galerie interactive, fiches animaux et mise en sc\u00e8ne immersive.',\n"
"            href: 'projets/zoo-fulbert.html',\n"
"            accent: ['#15803D', '#14532d'],\n"
"            symbol: '\U0001f981'\n"
"        },\n"
"        {\n"
"            title: 'Portfolio macOS',\n"
"            status: 'live',\n"
"            statusLabel: 'Ce site',\n"
"            year: '2026',\n"
"            stack: ['HTML', 'CSS', 'GSAP', 'Vanilla JS'],\n"
"            summary: 'Interface portfolio reproduisant l\u2019exp\u00e9rience macOS \u2014 dock magn\u00e9tique, fen\u00eatres glassmorphism, th\u00e8me clair/sombre et animations GSAP.',\n"
"            href: 'index.html',\n"
"            accent: ['#4F46E5', '#312e81'],\n"
"            symbol: '\U0001f4bb'\n"
"        }\n"
"    ],\n"
"    apps: [\n"
"        {\n"
"            title: 'IronPulse',\n"
"            status: 'wip',\n"
"            statusLabel: 'En cours',\n"
"            year: '2025',\n"
"            stack: ['React Native', 'Expo', 'Python', 'FastAPI'],\n"
"            summary: 'Application mobile de suivi fitness & nutrition. Dashboard d\u2019entra\u00eenement, journaux de s\u00e9ances et API REST Python.',\n"
"            href: 'projets/ironpulse.html',\n"
"            accent: ['#16A34A', '#14532d'],\n"
"            symbol: '\U0001f3cb\ufe0f'\n"
"        },\n"
"        {\n"
"            title: 'App Action',\n"
"            status: 'wip',\n"
"            statusLabel: 'En cours',\n"
"            year: '2026',\n"
"            stack: ['React', 'Vite', 'Node.js', 'CSS'],\n"
"            summary: 'Outil de gestion avec dashboards, suivi de t\u00e2ches par priorit\u00e9 et parcours produit orient\u00e9 d\u00e9mo client.',\n"
"            href: 'projets/app-action.html',\n"
"            accent: ['#2563EB', '#1e3a8a'],\n"
"            symbol: '\u26a1'\n"
"        },\n"
"        {\n"
"            title: 'Resolution Mate',\n"
"            status: 'live',\n"
"            statusLabel: 'D\u00e9ploy\u00e9',\n"
"            year: '2025',\n"
"            stack: ['Flutter', 'Dart', 'Firebase'],\n"
"            summary: 'Application mobile de gestion d\u2019objectifs. Suivi quotidien, visualisation de progression et rappels intelligents.',\n"
"            href: 'projets/resolution-mate.html',\n"
"            accent: ['#7C3AED', '#4c1d95'],\n"
"            symbol: '\U0001f3af'\n"
"        },\n"
"        {\n"
"            title: 'Mini Wiki PHP',\n"
"            status: 'live',\n"
"            statusLabel: 'Termin\u00e9',\n"
"            year: '2025',\n"
"            stack: ['PHP', 'MySQL', 'HTML', 'CSS'],\n"
"            summary: 'Encyclop\u00e9die web auto-h\u00e9berg\u00e9e. Cr\u00e9ation, \u00e9dition et recherche d\u2019articles avec gestion de cat\u00e9gories et de tags.',\n"
"            href: '#',\n"
"            accent: ['#B45309', '#78350f'],\n"
"            symbol: '\U0001f4da'\n"
"        }\n"
"    ],\n"
"    future: [\n"
"        {\n"
"            title: 'Projet Rust',\n"
"            status: 'upcoming',\n"
"            statusLabel: '\u00c0 venir',\n"
"            year: '2026',\n"
"            stack: ['Rust', 'WebAssembly'],\n"
"            summary: 'Mini application syst\u00e8me compil\u00e9e en WebAssembly. Performance native dans le navigateur, interface minimaliste et exp\u00e9rimentation bas-niveau.',\n"
"            href: '#',\n"
"            accent: ['#C2410C', '#7c2d12'],\n"
"            symbol: '\U0001f980'\n"
"        }\n"
"    ]\n"
"};\n"
)

with open('C:/Users/yohan/yohanstm-dev.github.io/portfolio-new.js', encoding='utf-8') as f:
    c = f.read()

cat_start = c.find('const finderCategoryLabels = {')
projects_end = c.find('\nconst skillCategories = [', cat_start)

print('Replacing bytes', cat_start, '->', projects_end)
result = c[:cat_start] + NEW_DATA + c[projects_end:]

with open('C:/Users/yohan/yohanstm-dev.github.io/portfolio-new.js', 'w', encoding='utf-8') as f:
    f.write(result)

print('Done. JS size:', len(result))
