// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtc9q0rX4VsIleZ2ZZurbSi8PGj52cxfo',
    appId: '1:122337503894:web:fef2dfc2c7075f06adb0b7',
    messagingSenderId: '122337503894',
    projectId: 'resolutionmate',
    authDomain: 'resolutionmate.firebaseapp.com',
    storageBucket: 'resolutionmate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3WFi_Zi9mub2fb8nNA8KQJm5y82Nx4hA',
    appId: '1:122337503894:android:d74591e050939a1aadb0b7',
    messagingSenderId: '122337503894',
    projectId: 'resolutionmate',
    storageBucket: 'resolutionmate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApfvzhf_QNMlZqCh4D9QUgwAdSSfKbwDM',
    appId: '1:122337503894:ios:70788df13b59f4a0adb0b7',
    messagingSenderId: '122337503894',
    projectId: 'resolutionmate',
    storageBucket: 'resolutionmate.firebasestorage.app',
    iosBundleId: 'com.example.resolutionMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApfvzhf_QNMlZqCh4D9QUgwAdSSfKbwDM',
    appId: '1:122337503894:ios:70788df13b59f4a0adb0b7',
    messagingSenderId: '122337503894',
    projectId: 'resolutionmate',
    storageBucket: 'resolutionmate.firebasestorage.app',
    iosBundleId: 'com.example.resolutionMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtc9q0rX4VsIleZ2ZZurbSi8PGj52cxfo',
    appId: '1:122337503894:web:163595d942011d15adb0b7',
    messagingSenderId: '122337503894',
    projectId: 'resolutionmate',
    authDomain: 'resolutionmate.firebaseapp.com',
    storageBucket: 'resolutionmate.firebasestorage.app',
  );
}
